services:
  msg-cleaner:
    container_name: msg-cleaner
    build: .
    restart: always
    env_file:
      - .env
    expose:
      - "${PORT:-8081}"
    # Descomente se precisar acessar de fora do Docker (debug, etc)
    # ports:
    #   - "8081:8081"
    networks:
      - chat-bridge

networks:
  chat-bridge:
    external: true
